import pickle, json, os, chromadb
bm25_dir = ".data/bm25_index"
with open(os.path.join(bm25_dir, "bm25_model.pkl"), "rb") as f: bm25 = pickle.load(f)
with open(os.path.join(bm25_dir, "doc_ids.json"), "r") as f: doc_ids = json.load(f)
with open(os.path.join(bm25_dir, "metadata.json"), "r") as f: meta = json.load(f)
print("=== BM25 ===")
print(f"corpus_size: {bm25.corpus_size}")
print(f"avgdl: {bm25.avgdl:.2f}")
print(f"doc_ids: {len(doc_ids)}")
print(f"Match: {bm25.corpus_size == len(doc_ids)}")
print(f"Primeros 3: {doc_ids[:3]}")
client = chromadb.PersistentClient(path=".data/chroma")
col = client.get_collection("hybridrank_elements")
print("\n=== ChromaDB ===")
print(f"count: {col.count()}")
print(f"metadata: {col.metadata}")
peek = col.peek(limit=2)
for i in range(len(peek["ids"])):
    print(f"  {peek['ids'][i]}: {peek['documents'][i][:80]}...")
    print(f"  embedding_dim: {len(peek['embeddings'][i])}")
chroma_ids = set(col.get(include=[])["ids"])
bm25_ids = set(doc_ids)
print(f"\nSolo BM25: {len(bm25_ids - chroma_ids)}")
print(f"Solo Chroma: {len(chroma_ids - bm25_ids)}")